name: Publish to Docker
on:
  push:
    branches:
      - main
jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      # Add your test steps here if needed...
      - name: Build container
        uses: docker/build-push-action@v3
        with:
          username: tshuto345
          password: ${{ secrets.GITHUB_TOKEN }}
          platforms: linux/amd64,linux/arm64
          registry: docker.pkg.github.com
          repository: tshuto345/publish-packages/game
          tag_with_sha: true
